logging:
  level:
    root: warn
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
server:
  port: 8080
